#!/bin/bash
echo "Content-type: text/html; charset-UTF-8;"
echo ""
echo "<html><body>"
echo "<meta name=viewport; content=width=device-width, initial-scale=1;>"
echo "<title>SEMINARIO</title>"
echo "<link rel=canonical; href=https://getbootstrap.com/docs/5.2/examples/sidebars/>"
echo "<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css; rel=stylesheet; integrity=sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx; crossorigin=anonymous:>"
echo "<script src=https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js; integrity=sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa; crossorigin=anonymous;></script>"
echo "<link href=../assets/dist/css/bootstrap.min.css; rel=stylesheet;>"
echo "<style>"
echo ".b-example-divider {height: 3rem;background-color: rgba(0, 0, 0, .1);border: solid rgba(0, 0, 0, .15);border-width: 1px 0;box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15); }"
echo ".b-example-vr {flex-shrink: 0;width: 1.5rem;height: 100vh;}"
echo "</style>"
echo "</head>"
