#!/usr/pkg/bin/bash
echo "Content-type: text/html; charset-UTF-8;"
echo ""
echo "<html><body>"
echo "<head>"
echo "<meta name=viewport; content=width=device-width, initial-scale=1;>"
echo "<title>SEMINARIO</title>"
echo "<link rel=canonical; href=https://getbootstrap.com/docs/5.2/examples/sidebars/;>"
echo "<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css; rel=stylesheet; integrity=sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx; crossorigin=anonymous;>"
echo "<script src=https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js; integrity=sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa; crossorigin=anonymous;></script>"
echo "<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">;"
echo "<style>"
echo ".b-example-divider {height: 3rem;background-color: rgba(0, 0, 0, .1);border: solid rgba(0, 0, 0, .15);border-width: 1px 0;box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15); }"
echo ".b-example-vr {flex-shrink: 0;width: 1.5rem;height: 100vh;}"
echo "</style>"
echo "</head>"
echo "<div class=container-fluid;>"
echo "<div class=row flex-nowrap;>"
echo "<div class=col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark;>"
echo "<div class=d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100;>"
echo "<a href="/" class=d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none;>"
echo "<span class=fs-5 d-none d-sm-inline;>Parcial IV</span>"
echo "</a>"
echo "<ul class=nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start; id=menu;>"
echo "<li>"
echo "<a href=ifconfig.html; class=nav-link px-0 align-middle;>"
echo "<i class=fs-4 bi-people></i> <span class=ms-1 d-none d-sm-inline>ifconfig</span></a>"
echo "</li>"
echo "<li>"

echo "<li>"
echo "<a href="#" class="nav-link px-0 align-middle">"
echo "<i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">ps $$/span></a>"
echo "</li>"
echo "</ul>"
echo "<hr>"
echo "</div>"
echo "</div>"
echo "<div class="b-example-divider b-example-vr"></div>"
echo "<div class="col py-3">"
echo "<h3>Nombre: Fredy Estuardo Reyes Del Cid</h3>"
echo "<h3>Carné: 5390-18-10587</h3>"
echo "<hr>"
echo "</div>"
echo "</div>"
echo "</div>"
echo "</body></html>"
